#!/usr/bin/env bash
# This will dig the DNS records
func () {
	dig "$2.$1" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", SUBDOMAIN, $4, $5}' SUBDOMAIN="$i"
}

declare -a arr=("www" "lb-01" "web-01" "web-02")

for i in "${arr[@]}"
do
	if [ "$2" == "$i" ]
	then
		func "$1" "$i"
	fi
	if [ -z "$2" ]
	then
		func "$1" "$i"
	fi
done
