#!/usr/bin/env bash
# Bash script that installs nginx
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo service nginx start
