#!/usr/bin/env bash
# Bash script that installs nginx and redirects to youtube page
new_conf="server_name\ _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=X_8Nh5XfRw0 permanent;"
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i "s@server_name\ _;@${new_conf}@g" /etc/nginx/sites-enabled/default
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo service nginx start
