#!/usr/bin/env bash
# Bash script that installs nginx and redirects to youtube page, and the 404 says something else
new_conf="server_name\ _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=X_8Nh5XfRw0 permanent;"
new_error="server_name\ _;\n\terror_page 404 /my_404.html;\nlocation = /my_404.html {\n\troot /var/www/html/;\n\tinternal;\n}"
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo touch /var/www/html/my_404.html && echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html
sudo sed -i "s@server_name\ _;@${new_conf}@g" /etc/nginx/sites-enabled/default
sudo sed -i "s@server_name\ _;@${new_error}@g" /etc/nginx/sites-enabled/default
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo service nginx start
