#!/usr/bin/env bash
# Bash script that installs nginx and adds custom header
new_header="server_name\ _;\n\tadd_header X-Served-By \$hostname;"
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i "s@server_name\ _;@${new_header}@g" /etc/nginx/sites-enabled/default
sudo service nginx start
