#!/usr/bin/env bash
# Bash script that installs nginx and redirects to youtube page, and the 404 says something else
new_conf="server_name\ _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=X_8Nh5XfRw0 permanent;"
new_error="server_name\ _;\n\terror_page 404 /my_404.html;\n\tlocation = /my_404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}"
new_header="http {\n\tadd_header X-Served-By \$hostname;"
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo touch /var/www/html/my_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html > /dev/null
sudo sed -i "s@server_name\ _;@${new_conf}@g" /etc/nginx/sites-enabled/default
sudo sed -i "s@server_name\ _;@${new_error}@g" /etc/nginx/sites-enabled/default
sudo sed -i "s@http {@${new_header}@g" /etc/nginx/nginx.conf
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo service nginx start
