#!/usr/bin/env bash
# fixing nginx
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen [::]:8080/listen [::]:80/g" /etc/nginx/sites-enabled/default
pkill nginx
sudo service nginx start
